name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # we need to fetch rust deps first to speed up cargo xtask
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          ~/.rustup
          target
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

    - id: cache-key
      run: echo "cache-key=$(cargo xtask build-tools --action-cache-key)" >> "$GITHUB_OUTPUT"

    - name: Cache build tools
      uses: actions/cache@v3
      with:
        path: build-tools # path where build-tools are installed
        key: ${{ steps.cache-key.outputs.cache-key }}
          
    - name: Install system tools
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build clang lld git libbpf-dev
        
    - name: Build-Tools (LLVM and bpf-linker)
      run: cargo xtask build-tools

    #- name: Save cached build tools
    #  uses: actions/cache@v3
    #  with:
    #    path: build-tools # path where build-tools are installed
    #    key: ${{ runner.os }}-build-tools-${{ hashFiles('xtask/src/**/*.rs') }}
      
    - name: Build (eBPF and userland)
      run: cargo xtask build
