name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build-Tools (LLVM and bpf-linker)
      run: cargo xtask build-tools
    - name: Build (eBPF and userland)
      run: cargo xtask build
