name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install system tools
      run: |
        sudo apt update
        sudo apt install -y qemu-system-x86 cmake ninja-build clang lld git libbpf-dev

    # we need to fetch rust deps first to speed up cargo xtask
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          ~/.rustup
          target
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock', '**/.github/workflows/ci.yml') }}

    - id: cache-key
      run: echo "cache-key=$(cargo xtask build-tools --action-cache-key)" >> "$GITHUB_OUTPUT"

    - name: Cache build tools
      uses: actions/cache@v3
      with:
        path: |
          build-tools/
        key: ${{ steps.cache-key.outputs.cache-key }}
              
    - name: Build-Tools (LLVM and bpf-linker)
      run: cargo xtask build-tools --free-space
      
    - name: Build (eBPF and userland)
      run: cargo xtask build --release

    - name: Linux Kernel LTS 5.4
      run: ./scripts/ci/test_kernel.sh 5.4
      
    - name: Linux Kernel LTS 5.10
      run: ./scripts/ci/test_kernel.sh 5.10

    - name: Linux Kernel LTS 5.15
      run: ./scripts/ci/test_kernel.sh 5.15

    - name: Linux Kernel LTS 6.1
      run: ./scripts/ci/test_kernel.sh 6.1
